"""Frozen synthetic inputs and offline expectations for the evidence diagnostic.

No model responses are recorded or generated by this module.
"""

from .diagnostic_cases import FACTS, case_records as binary_cases
from .judge import JudgeInput
from .prompts import content_hash
from .runner import Example

EVIDENCE_CASE_VERSION = "synthetic-evidence-attributes-numbers-v1"


def case_records():
    cases = []
    for original in binary_cases():
        issue = {"supported": "none", "contradicted": "contradiction",
                 "unknown": "insufficient_support"}[original["variant"]]
        cases.append({**original, "expected_issue_type": issue,
                      "expected_verdict": "unsupported" if original["expected_unsupported"] else "supported"})
    # Add negative availability controls: explicit false supports absence,
    # whereas unknown does not. Context is identical across short/embedded pairs.
    target = "The venue does not offer outdoor seating."
    for variant, value, issue in (("explicit-false", "False", "none"),
                                   ("unknown", "None", "insufficient_support")):
        context = "{'OutdoorSeating': " + value + "}. " + " ".join(FACTS)
        for length in ("short", "embedded"):
            answer = " ".join((*FACTS[:6], target, *FACTS[6:])) if length == "embedded" else target
            cases.append({"sample_id": f"absence-{variant}-{length}",
                          "input": {"answer": answer, "context": context},
                          "expected_unsupported": issue != "none",
                          "expected_issue_type": issue,
                          "expected_verdict": "supported" if issue == "none" else "unsupported",
                          "family": "absence", "variant": variant, "length": length})
    return tuple(cases)


def cases_sha256():
    return content_hash(case_records())


def examples():
    # Labels and case descriptors remain offline; only answer/context enter requests.
    return tuple(Example(r["sample_id"], JudgeInput(**r["input"])) for r in case_records())
